### ISSUE TITLE
Add missing developer documentation 

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/walrus-docs#5]
- [x] Client CLI, JSON mode, and daemon -> #16 
- [x] General developer guide (@gdanezis) -> #18 
- [x] Installation and configuration instructions (@mlegner) -> #21 
- [x] Walrus sites (@giac-mysten) -> #19 
- [ ] Public aggregator and publisher (@mlegner) -> #30
